---
title: "Data Science I Final Project: RQ and Data"
author: "Ayaka"
format: pdf
---

# Which factors best explain variation in receiving SNAP benefits in California vs Texas

something about historically red states and blue states

```{r setup}
library(tidyr)
library(tidycensus)
library(dplyr)
library(purrr)
library(here)
library(tidyverse)
library(psych)
library(ggplot2)
library(cluster)
library(GGally)
library(factoextra)
library(ggcorrplot)

```


### Pulling Data and Variables
```{r Generate a list}
# Creating list 
d <- c()
for (i in 1:49) {
  if (i < 10) {
    r <- paste("B01001_00", i, sep = "")
  }
  else {r <- paste("B01001_0", i, sep = "") }
  
  d <- c(d, r)
}
```

```{r Select Variables}
# Variable list for ACS pull
variables <- 
  c(# Pooulation
    'B01001_001',
    # Race
    'B02001_001', # Total Population
    'B02001_002', # White Alone
    'B02001_003', # Black or African American Alone
    'B02001_005', # Asian Alone
    'B02001_009', # Two or more races
    
    # Educational Attainment
    'B15003_001', # Total Education Population
    'B15003_017', # High School Diploma
    'B15003_022', # Bachelor's Degree
    'B15003_025', # Doctorate Degree
    
    # Housing Status
    'B25003_001', # Total Housing Units
    'B25003_002', # Owner Occupied
    'B25003_003', # Renter Occupied
    
    # Geographic Mobility by Citizenship
    'B07007_001', # Total Population for Mobility
    'B07007_002', # Native Population
    'B07007_003', # Foreign Born Population
    
    # Language Spoken at Home
    "B16001_001", # Total population age 5+ 
    "B16001_002", # Speak only English at home
    
    # Poverty Status
    "B17001_001", # Total 
    "B17001_002", # Income in the past 12 months below poverty level
    
    # Transportation to Work
    "B08006_001",  # Total workers
    "B08006_008",  # Public transportation
    
    # Travel time to work
    "B08303_001", # Total workers
    "B08303_013", # Workers with commute time 90 or more minutes
    
    # Family Characteristics/Structure 
    "B09002_001",  # Total population in families
    "B09002_002",  # In married-couple families
    
    # Employment Status
    "B23025_001", # Total Population 16+
    "B23025_005"  # Unemployed
    )
```

# Data

```{r data}
both <- get_acs(geography = "county", 
                state = c("CA", "TX"),
                variables = variables, 
                year = 2024,
                survey = "acs1") 
pop <- both %>%
  filter(variable == "B01001_001") %>%
  select(GEOID, population = estimate)

both <- both %>%
  left_join(pop, by = "GEOID") %>%
  mutate(normalized_estimate = estimate / population) %>% 
  select(GEOID, NAME, variable, population, normalized_estimate) %>%
  pivot_wider(
    names_from = variable,
    values_from = normalized_estimate
  )


```

# EDA

```{r eda, warning=FALSE}
sum(is.na(both))
both <- na.omit(both)
sum(is.na(both))

# Check for correlation among variables & remove highly correlated variables
GGally::ggcorr(both, size = 2)

# Numeric columns only for analyses
both_num <- both %>%
  dplyr::select(-c(GEOID, NAME))
```


# PCA

```{r pca}
# B01001_001 has 0 variance since variables are normalized by population
zero_variance_cols <- names(both_num)[apply(both_num, 2, var, na.rm = TRUE) == 0]
both_num <- both_num[, !(names(both_num) %in% zero_variance_cols)]

pca <- prcomp(both_num, scale. = TRUE)
loadings <- as.data.frame(pca$x)

mapply(shapiro.test, both_num)

mardia(both_num)
KMO(both_num)
cortest.bartlett(both_num)
fa.parallel(both_num, fa = "fa")
```

# Clustering

```{r clustering}

Xsc <- scale(both_num)

set.seed(100)

m <- c( "average", "single", "complete", "ward")
names(m) <- c( "average", "single", "complete", "ward")
ac <- function(x) {
  agnes(Xsc, method = x)$ac
  }
purrr::map_dbl(m, ac)

distance <- dist(Xsc, method = "euclidean")
hc_complete <- hclust(distance, method = 'ward.D2')
plot(hc_complete)

plot <- fviz_dend(hc_complete, k = 2)
plot +
  theme_minimal() +
  labs(title = "Dendrogram based on Hierarchical Clustering")

sub_grp <- cutree(hc_complete, 2)


```